---
name: HTML-TableParser-Grid
version: v0.0.1
author:
  - 'Takeru INOUE <takeru.inoue@gmail.com>'
abstract: Provide access methods to HTML tables by indicating row and column
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  HTML::TableParser: 0
  Test::More: 0
  version: 0
provides:
  HTML::TableParser::Grid:
    file: lib/HTML/TableParser/Grid.pm
    version: v0.0.1
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
