---
name: HTML-TableParser-Grid
version: 0.0.4
author:
  - 'Takeru INOUE <takeru.inoue _ gmail.com>'
abstract: Provide access methods to HTML tables by indicating row and column
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  HTML::TableParser: 0
  version: 0
build_requires:
  Test::Exception: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Perl::Critic: 0
provides:
  HTML::TableParser::Grid:
    file: lib/HTML/TableParser/Grid.pm
    version: 0.0.4
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
